version: "3.8"

services:
  product-service:
    image: app1.jar
    container_name:  heuristic_sinoussi
    build:
      context: ./product-service
      args:
        - APP_NAME=product-service
        - APP_VERSION=0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: dev
    expose:
      - 8080
   ports:
     - 8080:8080
  review-service:
    image: app.jar
    container_name:  unruffled_ellis
    build:
      context: ./rate-service
      args:
        - APP_NAME=rate-service
        - APP_VERSION=0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: dev
   expose:
      - 8080
   ports:
      - 8080:8080